#!/usr/bin/env bash

ROOT_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")"/..)"
cd "${ROOT_DIR}" || exit $?

exec retry -- rsync "$@" --exclude=*.sqlite -Pavh -e ssh vultr:~/code/dbsentinel/data/ data
